version: '3'
services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
      - mongodb_volume_configdb:/data/configdb mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: passwordMongo2020
  redis:
    image: "redis:latest"
    ports: 
      - "6379:6379"
volumes:
  mongodb_volume:
  mongodb_volume_configdb: